# -*- coding: utf-8 -*-
"""simulacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Jovilo01/Simula-o_MonteCarlos_POII/blob/main/simulacao.ipynb
"""

import random
import matplotlib.pyplot as fig

rep_dados = int(input('Digite n amostral desejado: '))
rep_exp = int(input('Digite o número de repetições do experimento que deseja: '))
ei = int(input('Digite o estoque inicial: '))
pp = int(input('Digite ponto de pedido (estoque mínimo): '))
pedido = int(input('Digite quantidade de pedido: '))
pedidomax = int(input('Digite quantidade de pedido maximo: '))

print ("B=BLOCO, D=DEMANDA, EF=ESTOQUE FINAL, DA=DEMANDA ATENDIDA E EA=ESTOQUE ATUAL")

amostra = [1, 2, 3, 4]
w = [15,15,55,15]
aumentopedido = []


while pedido <= pedidomax:
 mm = []
 somamm = 0
 miam = []
 somaiam = 0

 cont_repet_exp = 1
 while cont_repet_exp <= rep_exp:
  e = ei
  soma = 0
  somada = 0
  aleat = []

  for i in range(rep_dados):
    x = random.choices(amostra, w)
    print ('B:', x, end= " ")
    if x[0] == 1:
      x2 = random.randint(1,70)
      print ('D:', x2, end= " ")
      aleat.append(x2)
      soma += x2           
    elif x[0] == 2:
      x2 = random.randint(71,120)
      print ('D:', x2, end= " ")
      aleat.append(x2) 
      soma += x2
    elif x[0] == 3:
      x2 = random.randint(121,170)
      print ('D:', x2, end= " ")
      aleat.append(x2) 
      soma += x2
    else:
      x2 = random.randint(171,320)
      print ('D:', x2, end= " ")
      aleat.append(x2) 
      soma += x2 

    e = e - x2
    if e < 0:
      da  = e + x2
      e = 0
    else:
      da = x2

    print ('DA:', da, end=" ")
    somada += da
    print ('EF:', e, end=" \n")
    if e <= pp:
      e += pedido
      print ('EA:', e, end= " \n")
    else:
      print ('EA:', e, end= " \n")

  media = soma / rep_dados 
  print ("Média da demanda: ", media, end= "\n") 
  ia = somada / soma 
  print ("Indice de atendimento: ", ia, end= "\n\n")
  somamm += media
  somaiam += ia
  mm.append(media)
  miam.append(ia)
  cont_repet_exp += 1
 mediam = somamm / rep_exp
 mediaiam = somaiam / rep_exp
 print ("Medias das amostras: ", mm)
 print ("Indices de atendimento: ", miam)
 print ("Média das medias de demanda: ", mediam, end= "\n")
 print ("Média de atendimento: ", mediaiam, end= "\n\n")
 aumentopedido.append(mediaiam)
 pedido += 1
print ("indices de atendimentos verificados: ", aumentopedido)
fig.plot(aumentopedido)

